### ISSUE TITLE
Git force push unterbinden

### ISSUE THREAD

**Issue by Petikoch** [ReactiveMeetupLucerne/AsyncNonBlockingExamplesJVM#3]
... wegen Jarek ;-)

**Comment by McPringle** [comment]
Scheint leider nicht bei github.com zu gehen sondern nur bei GitHub Enterprise: 
https://help.github.com/enterprise/2.8/admin/guides/developer-workflow/blocking-force-pushes-to-a-repository/

**Comment by McPringle** [comment]
Korrektur: Es gibt doch eine Möglichkeit, GitHub hat "Protected Branches" eingeführt, die genau das machen, was wir wollen! "Repository Settings" öffnen, "Branches" Tab auswählen und dann "Protect Branches"!

**Comment by Petikoch** [comment]
Danke vielmals @McPringle für die Recherche! master ist nun geschützt vor "forced push" :-)
