### ISSUE TITLE
Creating RxJava 1.x Observables using create?

### ISSUE THREAD

**Issue by TexasFred** [ReactiveMeetupLucerne/AsyncNonBlockingExamplesJVM#6]
Hi everybody,

me again... Fred.

I'm very interested in RxJava and I'am reading the "Reactive Programming with RxJava" book (http://shop.oreilly.com/product/0636920042228.do). The book states, that it's tricky to use `Observable#create`. Issues like backpressure and unsubscribing must be handled yourself... very error prone and hard to get really right. Also the RxJava Wiki says `create( ) — advanced use only! create an Observable from scratch by means of a function, consider fromEmitter instead` in https://github.com/ReactiveX/RxJava/wiki/Creating-Observables.

This example uses `Observable#create`:

https://github.com/ReactiveMeetupLucerne/AsyncNonBlockingExamplesJVM/blob/master/src/main/java/challenge1/rxjava1/RxJavaObservableExample.java

Wouldn't it be simpler and more safe to just use `Observable#fromCallable` or `Observable#fromEmitter`?

Best regards,
Fred

**Comment by Petikoch** [comment]
Thanks @TexasFred for the input. I'll check this...

**Comment by TexasFred** [comment]
Ah... looks much better. Thanks!
