### ISSUE TITLE
Aggregating in RxJava2Example (challenge 1)

### ISSUE THREAD

**Issue by TexasFred** [ReactiveMeetupLucerne/AsyncNonBlockingExamplesJVM#7]
Hello again :-)

You have kind of interesting way of aggregating the values of a Flowable... you use shared mutual state in 

https://github.com/ReactiveMeetupLucerne/AsyncNonBlockingExamplesJVM/blob/master/src/main/java/challenge1/rxjava2/RxJava2Example.java

This doesn't look really ideamatic. Why don't you use a built in aggregation operator like http://reactivex.io/documentation/operators/reduce.html or `toList` ? Using `reduce` is really simple...

		Flowable.just(4,5,7)
				.reduce((number1, number2) -> number1 + number2)
				.map(sum -> sum / 3.0)
				.subscribe(avg -> System.out.println(avg));

Your example would be very shorter...

What do you think?

Best regards,
Fred

**Comment by TexasFred** [comment]
Another one regarding this example... Why do you use a separate ExecutorService (`Executors.newCachedThreadPool()`). What about using the built in `Schedulers.io()` ?

Thanks for your feedback, Fred.

**Comment by Petikoch** [comment]
@McPringle was denkst Du?

**Comment by McPringle** [comment]
@Petikoch @TexasFred Sounds good, if you like you can implement your suggestion. Our example solution would be better then.
