### ISSUE TITLE
CompletableFuture and Timeouts in challenge 2

### ISSUE THREAD

**Issue by TexasFred** [ReactiveMeetupLucerne/AsyncNonBlockingExamplesJVM#8]
Hi,

Hmmm... just reading

https://github.com/ReactiveMeetupLucerne/AsyncNonBlockingExamplesJVM/blob/master/src/main/java/challenge2/java8/GmoCompletableFutureDemo.java

This looks kind of low levelish... `Thread#sleep`, `Thread#isAlive`, `Thread#interrupt`... I wouldn't like to maintain that piece of code, especially if there are no unit tests!

What about making it simpler and don't mix levels of abstractions that much? In http://stackoverflow.com/a/24457111 is a `supplyAsync` method with timeout. What about using something like that?

An interesting article is also http://www.nurkiewicz.com/2014/12/asynchronous-timeouts-with.html, but this looks very complicated. 

Thanks for your feedback.

Best regards,
Fred

**Comment by Petikoch** [comment]
@gmo123 was hälst Du davon?

**Comment by gmontalta** [comment]
Hi @TexasFred,

We uploaded another Java 8 example using your hints:
https://github.com/ReactiveMeetupLucerne/AsyncNonBlockingExamplesJVM/blob/master/src/main/java/challenge2/java8/GmoCompletableFutureDemo2.java
What do you think?

Also, we did a Java 9 version using the new "completeOnTimeout" function:
https://github.com/ReactiveMeetupLucerne/AsyncNonBlockingExamplesJVM/blob/master/src/main/java/challenge2/java9/GmoCompletableFutureDemoJava9.java
(Our build system does not support Java 9, hence we uploaded this as .txt file. )
Do you maybe have a better solution for "executor.shutdownNow()"?

Thanks,
Gregor

**Comment by Petikoch** [comment]
I did some cleanup... 

https://github.com/ReactiveMeetupLucerne/AsyncNonBlockingExamplesJVM/blob/master/src/main/java/challenge2/java8/GmoCompletableFutureDemo2.java

**Comment by TexasFred** [comment]
Hello @gmo123 ,

I like the second JDK 8 version! 

Regarding the JDK 9 version... cool, that there is something "better" in JDK 9! But... the "executor.shutdownNow()" looks really ugly and like a hack. I don't know why the `completeOnTimeout` method doesn't interrupt the other thread. 

Best regards,
Fred
