### ISSUE TITLE
RxJava Example for challenge 3?

### ISSUE THREAD

**Issue by TexasFred** [ReactiveMeetupLucerne/AsyncNonBlockingExamplesJVM#9]
Hi there,

I'm wondering why there isn't yet an example for challenge 3 using RxJava?

This would be rather easy and show the power of those reactive libraries, I guess... something like 

		Observable<Integer> temperatureValues = Observable.interval(2, TimeUnit.SECONDS, Schedulers.io())
				.map(tick -> ThreadLocalRandom.current().nextInt(20, 25))
				.doOnNext(tempValue -> System.out.println(Thread.currentThread().getName() + " -> " + tempValue + "°Celsius from temperature source"));

		Observable<Pair<Integer, Integer>> minMaxValuesWithinWindow = temperatureValues.window(10, TimeUnit.SECONDS, Schedulers.computation())
				.flatMap(temperatureValuesWithinWindow ->
						temperatureValuesWithinWindow.reduce(
								Pair.of(Integer.MAX_VALUE, Integer.MIN_VALUE),
								(minMaxPair, tempValue) -> {
									int newMin = minMaxPair.getLeft();
									if (tempValue < newMin) {
										newMin = tempValue;
									}
									int newMax = minMaxPair.getRight();
									if (tempValue > newMax) {
										newMax = tempValue;
									}
									return Pair.of(newMin, newMax);
								}
						).toObservable()
				);

		minMaxValuesWithinWindow.subscribe(minMaxPair -> System.out.println(Thread.currentThread().getName() + " -> Within window: Min=" + minMaxPair.getLeft() + "°Celsius, Max=" + minMaxPair.getRight() + "°Celsius. Calculated async and non-blocking TM :-)"));

would do the Job. Of course, you have the funny "legacy" `TemperatureValueSource` with listeners and stuff. But I guess this `TemperatureValueSource` could be rather easily converted into an `Observable` using the `fromEmitter` operator.

What do you think?

Best regards,
Fred

**Comment by TexasFred** [comment]
Here's more advanced example showing how to deal with backpressure... there is a very speedy temparture source using one CPU 100% to generate values. We need to somehow "throttle" it by e.g. dropping values and e.g. "thinning" it using `sample`:

		Observable<Integer> speedyTemperatureSource = Observable.range(1, Integer.MAX_VALUE).subscribeOn(Schedulers.computation())
				.map(tick -> ThreadLocalRandom.current().nextInt(20, 25));

		speedyTemperatureSource.sample(2, TimeUnit.SECONDS)
				.subscribe(tempValueSample -> System.out.println(Thread.currentThread().getName() + " -> " + tempValueSample + "°Celsius sample from temperature source"));

		Flowable<Triple<Integer, Integer, Integer>> minMaxValuesWithinWindow = speedyTemperatureSource
				.toFlowable(BackpressureStrategy.DROP)
				.sample(1, TimeUnit.MILLISECONDS)
				.window(10, TimeUnit.SECONDS, Schedulers.computation())
				.flatMap(temperatureValuesWithinWindow ->
						temperatureValuesWithinWindow.reduce(
								Triple.of(Integer.MAX_VALUE, Integer.MIN_VALUE, 0 /* count */),
								(minMaxCountTriple, tempValue) -> {
									int newMin = minMaxCountTriple.getLeft();
									if (tempValue < newMin) {
										newMin = tempValue;
									}
									int newMax = minMaxCountTriple.getMiddle();
									if (tempValue > newMax) {
										newMax = tempValue;
									}
									return Triple.of(newMin, newMax, minMaxCountTriple.getRight() + 1);
								}
						).toFlowable()
				);

		minMaxValuesWithinWindow.subscribe(minMaxCountTriple -> System.out.println(
				Thread.currentThread().getName()
						+ " -> Within window: Min="
						+ minMaxCountTriple.getLeft() 
						+ "°Celsius, Max=" + minMaxCountTriple.getMiddle()
						+ "°Celsius. Got " + minMaxCountTriple.getRight()
						+ " values. Calculated async and non-blocking TM :-)"));



Output 

```
RxComputationThreadPool-1 -> 23°Celsius sample from temperature source
RxComputationThreadPool-1 -> 21°Celsius sample from temperature source
RxComputationThreadPool-1 -> 21°Celsius sample from temperature source
RxComputationThreadPool-1 -> 22°Celsius sample from temperature source
RxComputationThreadPool-1 -> 22°Celsius sample from temperature source
RxComputationThreadPool-4 -> Within window: Min=20°Celsius, Max=24°Celsius. Got 83669658 values. Calculated async and non-blocking TM :-)
RxComputationThreadPool-1 -> 21°Celsius sample from temperature source
RxComputationThreadPool-1 -> 22°Celsius sample from temperature source
RxComputationThreadPool-1 -> 22°Celsius sample from temperature source
RxComputationThreadPool-1 -> 21°Celsius sample from temperature source
RxComputationThreadPool-1 -> 21°Celsius sample from temperature source
RxComputationThreadPool-4 -> Within window: Min=20°Celsius, Max=24°Celsius. Got 112158296 values. Calculated async and non-blocking TM :-)
...
```

Isn't that cool!?

**Comment by Petikoch** [comment]
Hi @TexasFred ,

thanks for the input!

I added the two examples from you... 

https://github.com/ReactiveMeetupLucerne/AsyncNonBlockingExamplesJVM/blob/master/src/main/java/challenge3/rxjava2/Challenge3RxJava2Example.java

https://github.com/ReactiveMeetupLucerne/AsyncNonBlockingExamplesJVM/blob/master/src/main/java/challenge3/rxjava2/Challenge3RxJava2ExampleWithThrotteling.java

I modified them slightly, I hope this is ok?

Best regards,
Peti
